### ISSUE TITLE
Please add support for FlowSmart Control Meter & Valve Controller

### ISSUE THREAD

**Issue by miztahsparklez** [dkerr64/homebridge-yolink#100] opened 2024-08-03 08:34 UTC
Hello,

I've recently added a new water valve/flow meter to my hub and noticed I've been getting errors in my log (I've redacted some identifiers, but let me know if this is required):

YoLink device type: 'WaterMeterController' is not supported (YS5006-UC (xxxxx) YoLink Water Meter) (handleGet)
Please report all bugs at https://github.com/dkerr64/homebridge-yolink/issues
{
  "state": {
    "valve": "open",
    "meter": 7828
  },
  "alarm": {
    "openReminder": false,
    "leak": false,
    "amountOverrun": false,
    "durationOverrun": false,
    "valveError": false,
    "reminder": false,
    "freezeError": false
  },
  "battery": 4,
  "powerSupply": "PowerLine",
  "valveDelay": {
    "ch": 1,
    "off": 0
  },
  "attributes": {
    "openReminder": 0,
    "screenMeterUnit": 0,
    "meterUnit": 0,
    "alertInterval": 0,
    "meterStepFactor": 10,
    "leakLimit": 10,
    "autoCloseValve": true,
    "overrunAmountACV": false,
    "overrunDurationACV": false,
    "leakPlan": "schedule",
    "overrunAmount": 500,
    "overrunDuration": 150
  },
  "version": "0603",
  "tz": -7,
  "recentUsage": {
    "amount": 33,
    "duration": 23
  },
  "loraInfo": {
    "netId": "010201",
    "devNetType": "D",
    "signal": -36,
    "gatewayId": "XXXXX",
    "gateways": 2
  }
}

I'm not quite sure what data I would expect to see, but I know some of my other devices (like washer/dryer) will show a faucet icon in home with a timer of how long it runs.

Thanks!

**Comment by dkerr64** [comment] 2024-08-03 09:17
Duplicate of #98 please read discussion in there and try installing plugin beta.

**Closed by dkerr64** 2024-08-03 09:17 UTC
Labels: enhancement
