### ISSUE TITLE
Homebridge main UI Screen - Message - Yolink Slows Homebridge

### ISSUE THREAD

**Issue by ericsabc** [dkerr64/homebridge-yolink#75] opened 2023-04-01 17:57 UTC
**Describe The Bug:**
[4/1/2023, 1:46:04 PM] [homebridge-yolink] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! 
**To Reproduce:**
Start Homebridge with Yolink plugin installed
**Expected behavior:**
No Error Message
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:1.3.4
* **Homebridge Version**: <1.6.0>
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by dkerr64** [comment] 2023-04-01 18:45
@ericsabc I am guessing that you are seeing this during or shortly after restarting Homebridge or the child bridge that holds this plugin.  It is a side affect of YoLink being unable to connect to one of your devices.  Some devices seem more prone to it than others (e.g. smart outlets) but I have seen it with all of them.

YoLink returns an "unable to connect" error, and this plugin will keep retrying until it eventually connects, this can take 10 minutes or more but, as far as I can tell, it always succeeds eventually.

In the meantime, the plugin is unable to handle requests from Homebridge/Homekit for the device in question, the handlers are not initialized yet.  And this is the cause of the _This plugin slows down Homebridge_ message.

I don't believe that there is anything I can do to fix this.  I believe it better to not respond than to respond with incorrect data or indicating that an action (turn on/turn off) was completed when it was not.

To minimize the impact on Homebridge / HomeKit do [run this plugin in its own child bridge.](https://github.com/homebridge/homebridge/wiki/Child-Bridges)

Thanks
David

**Comment by ericsabc** [comment] 2023-04-01 20:14
Thanks David. Very solid plugin!

Best,
Eric

**Comment by dkerr64** [comment] 2023-06-09 21:19
Closing this issue as the problem is, unfortunately, somewhat expected and resolves itself after some time.

**Closed by dkerr64** 2023-06-09 21:19 UTC
Labels: bug
